service: iogym-public
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${file(./.env.yml):stage}
  region: ${file(./.env.yml):region}
  role: ${file(./.env.yml):aws-role}
  vpc:
    securityGroups: ${file(./.env.yml):security-groups}
    subnets: ${file(./.env.yml):subnets}
  environment: ${file(./.env.yml):environment}

package:
  exclude:
    - .git/**
    - .gitignore
    - .env.yml
    - .eslintrc.json

functions:
  # Users
  getUsersByGym:
    handler: users/handler.getUsersByGym
    events:
      - http:
          path: /gyms/{gymId}/users
          method: GET
          cors: true
          resp: http
          request:
            parameters:
              paths:
                gymId: true
  addUserToGym:
    handler: users/handler.addUserToGym
    events:
      - http:
          path: /gyms/{gymId}/users/{userId}
          method: POST
          cors: true
          resp: http
          request:
            parameters:
              paths:
                gymId: true
                userId: true
  removeUserFromGym:
    handler: users/handler.removeUserFromGym
    events:
      - http:
          path: /gyms/{gymId}/users/{userId}
          method: DELETE
          cors: true
          resp: http
          request:
            parameters:
              paths:
                gymId: true
                userId: true
  getUserById:
    handler: users/handler.getUserById
    events:
      - http:
          path: /users/{userId}
          method: GET
          cors: true
          resp: http
          request:
            parameters:
              paths:
                userId: true
  createUser:
    handler: users/handler.createUser
    events:
      - http:
          path: /users
          method: POST
          resp: http
  removeUser:
    handler: users/handler.removeUser
    events:
      - http:
          path: /users/{userId}
          method: DELETE
          cors: true
          resp: http
          request:
            parameters:
              paths:
                userId: true
  getGymsByUser:
    handler: users/handler.getGymsByUser
    events:
      - http:
          path: /users/{userId}/gyms
          method: GET
          cors: true
          resp: http
          request:
            parameters:
              paths:
                userId: true
  
  # Sessions
  getSessionsByUser:
    handler: sessions/handler.getSessionsByUser
    events:
      - http:
          path: /users/{userId}/sessions
          method: GET
          cors: true
          resp: http
          request:
            parameters:
              paths:
                userId: true
  getSessionById:
    handler: sessions/handler.getSessionById
    events:
      - http:
          path: /sessions/{sessionId}
          method: GET
          cors: true
          resp: http
          request:
            parameters:
              paths:
                sesssionId: true
  updateSessionById:
    handler: sessions/handler.updateSessionById
    events:
      - http:
          path: /sessions/{sessionId}
          method: PUT
          cors: true
          resp: http
          request:
            parameters:
              paths:
                sesssionId: true
  getFramesBySession:
    handler: sessions/handler.getFramesBySession
    events:
      - http:
          path: /sessions/{sessionId}/frames
          method: GET
          cors: true
          resp: http
          request:
            parameters:
              paths:
                sesssionId: true
